import '../scss/style.scss'
import './swiper.js'
import './openContent.js'
import './closeContent.js'
import './companyInfoOpen.js'
import './readMore.js'
import './initFirstSwiper.js'
import './initSecondSwiper.js'
import './burger.js'
import './windowEvent.js'
import './opacityClose.js'
import './feedback.js'
import './orderCall.js'

